error_handling:
  circuit_breaker:
    failure_threshold: 5
    success_threshold: 2
    timeout_duration: 300
  max_retries: 3
  retry_delay: 2
google_drive:
  enabled: true
  folder: BG_Screenshots
screenshot:
  interval: 60
  local_folder: E:/Users/maracudev/OneDrive/Imágenes/BG_Screenshots
  prefix: screenshot
  region:
    - 66
    - 145
    - 1707
    - 1089
